apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-user: "{{ .admin_user }}"
        admin-password: "{{ .admin_password }}"
  data:
    - secretKey: admin_user
      remoteRef:
        key: observability/grafana
        property: admin_user
    - secretKey: admin_password
      remoteRef:
        key: observability/grafana
        property: admin_password
