apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  source:
    repoURL: https://<your-org>.github.io/eks-observability-helm-charts
    chart: thanos
    targetRevision: 1.0.0
    helm:
      releaseName: thanos
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: { prune: false, selfHeal: true, allowEmpty: false }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff: { duration: 5s, factor: 2, maxDuration: 1m }
