apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secret-store
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/<your-org>/eks-observability-gitops.git
    targetRevision: main
    path: manifests/external-secrets/base
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated: { prune: false, selfHeal: true, allowEmpty: false }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff: { duration: 5s, factor: 2, maxDuration: 1m }
