# ClusterSecretStore tells External Secrets WHERE to fetch secrets from.
# Backed by AWS Secrets Manager via the IRSA role created by eks-observability-iac.
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  labels:
    app.kubernetes.io/component: secrets-management
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
